drop table if exists achievements CASCADE;
drop table if exists person CASCADE;
create table achievements (id integer generated by default as identity, achievement varchar(255) not null, complete boolean not null, fk_person_id integer, primary key (id));
create table person (person_id integer generated by default as identity, age integer not null check (age>=16), name varchar(255), primary key (person_id));
alter table achievements add constraint UK_2vg3fxh94k3o44t9dfx9f1bb6 unique (achievement);
alter table achievements add constraint FKp1astmnc40nymfxqtpqj40m5 foreign key (fk_person_id) references person on delete cascade;